food_groups:
  grains_and_tubers:
    weight: 2
    target_g: 100
  vegetables:
    weight: 3
    target_g: 400
  fruits:
    weight: 3
    target_g: 275
  livestock_poultry_meat:
    weight: 2
    target_g: 60
  aquatic_products:
    weight: 2
    target_g: 60
  eggs:
    weight: 2
    target_g: 50
  dairy:
    weight: 2
    target_g: 300
  soy_products:
    weight: 1
    target_g: 20
  nuts:
    weight: 1
    target_g: 10